---
- name: Ensure Fail2ban is installed
  community.general.pacman:
    name: fail2ban
    state: present

- name: Ensure Fail2ban service is enabled and running
  ansible.builtin.systemd_service:
    name: fail2ban.service
    enabled: true
    state: started

- name: Deploy SSH jail configuration
  ansible.builtin.template:
    src: sshd.local.j2
    dest: /etc/fail2ban/jail.d/sshd.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart Fail2ban
