---
- name: Demonstrate Anible handlers
  hosts: servers
  become: true
  gather_facts: false

  tasks:
    - name: Create Docker management configuration
      ansible.builtin.copy:
        content: |
          # This file is managed by Ansible.
          # Handler demonstration
        dest: /etc/docker-ansible-test.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart Docker

  handlers:
    - name: Restart Docker
      ansible.builtin.systemd_service:
        name: docker
        state: restarted
